name: srmcapp
description: A new MathOlympiad Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_tex: ^3.6.7+8
  provider: ^3.1.0
  pie_chart: ^3.1.1
  flutter_rating_bar: ^3.0.1+1
  flutter_spinkit: ^4.1.2+1
  image_picker: ^0.6.6+4
  image_cropper: ^1.2.2
  rflutter_alert: ^1.0.3
  fluttertoast: ^4.0.0
  connectivity: ^0.4.8+6
  syncfusion_flutter_charts: ^18.4.35
  splashscreen: ^1.2.0
  email_validator: ^1.0.5
  google_sign_in: ^4.5.9
  http: ^0.12.2
  flushbar: ^1.10.4
  firebase_messaging: ^7.0.3
  firebase_core : ^0.5.0
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  firebase_auth: ^0.18.1+2
  flutter_switch: ^0.2.0
  group_radio_button: ^1.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
